name: project-78-check
run-name: ${{ github.actor }}

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Java JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '20'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2.1
          arguments: build
          build-root-directory: app